# name = input("nhập tên:")
# gender = input ("nhập giới tính:")
# sk = input ("nhập sở thích:")
# diu = input ("nhập món ăn dị ứng:")
# print (" tên thú cưng:",name)
# print ("giới tính :",gender)
# print ("sở thích :",sk)
# print ("dị ứng :",diu)

# age = int (input ("nhập tuổi:"))
# print ("10 nam nua, bạn",age + 10,"tuổi")
# print ("100 nam nua, bạn",age + 100,"tuổi")

# print ("chào mừng tới ứng dụng curentcy Converted - chuyển đổi tiền tệ")
# dollar = int (input ("nhập số tiền cần đổi (dola Mỹ): $"))
# print ("số tiền quy ra Việt Nam đồng (VNĐ)")
# print ("$",dollar,"quy đổi ra được",dollar * 26000,"đ")

# x = input().split()
# a = int ( x [0] )
# b = int ( x [1] )
# print (a,end = "")
# print ("+",end = "")
# print (b,end = "")
# print ("=",end = "")
# print (a + b,end = "")
print ((16 - 13 // 4) % 4)