# print ("*")
# print ("**")
# print ("***")
# print ("****")
# print ("*****")
# print ("******")
# print ("*******")
# print ("********")
# print ("*********")
# print ("**********")
# print ("***********")
# print ("************")
print ("Họ và tên : Trần Tiến Khoa")
print ("Ngày sinh : 13/7/2010")
print ("Quê quán : TP Hồ Chí Minh")
print ("Sở thích : xem tv")